kind: Pod
apiVersion: v1
metadata:
  name: name
  namespace: airflow
  labels:
    mylabel: foo
spec:
  containers:
    - name: base
      image: dbnd-example:latest
      env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: databand-secrets
              key: sql_alchemy_conn
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws_secret_access_key
      resources: {}
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
